apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  type: LoadBalancer
  selector:
    app: metabase
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-nodeport
spec:
  type: NodePort
  selector:
    app: metabase
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30010