{{ if .Values.apps }}{{ if .Values.apps.postgresql }} {{ if .Values.apps.postgresql.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  selector:
    app: {{ .Release.Name }}-postgres-headless
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
{{ end }}{{ end }}{{ end }}