{{ if .Values.apps }}{{ if .Values.apps.postgresql }} {{ if .Values.apps.postgresql.enabled }} 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-configs
  labels:
    app: {{ .Release.Name }}-postgres
data:
  POSTGRES_HOST: {{ .Release.Name }}-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_PASSWORD: password
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
{{ end }}{{ end }}{{ end }}