{{ if .Values.apps }}{{ if .Values.apps.mysql }} {{ if .Values.apps.mysql.enabled }} {{ if .Values.isAppliance }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-mysql-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
spec:
  capacity:
    storage: {{  .Values.apps.mysql.storage.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Release.Name }}-mysql-storage
  local:
    path: {{ .Values.mysqlLocalPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  storageClassName: {{ .Release.Name }}-mysql-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{  .Values.apps.mysql.storage.size }}
{{ end }}{{ end }}{{ end }}{{ end }}