{{ if .Values.apps }}{{ if .Values.apps.openmrs }} {{ if .Values.apps.openmrs.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openmrs
  labels:
    app: {{ .Release.Name }}-openmrs
spec:
  selector:
    app: {{ .Release.Name }}-openmrs
  ports:
  - name: '80'
    protocol: TCP
    port: 80
    targetPort: 8080 
  - name: '8080'
    protocol: TCP
    port: 8080
    targetPort: 8080
{{ end }}{{ end }}{{ end }}