apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-mart
spec:
  selector:
    matchLabels:
      app: bahmni-mart
  template:
    metadata:
      labels:
        app: bahmni-mart
    spec:
      volumes:
        - name: distro
          persistentVolumeClaim:
            claimName: distro-pvc
        - name: mart-props-vol
          configMap:
            name: mart-props
        - name: mart-db-init
          configMap:
            name: postgres-db-scripts
      initContainers:
        - name: init-db
          image: postgres:alpine
          volumeMounts:
            - name: mart-db-init
              mountPath: "/mnt/"
          command: ['sh', '-c', "bash /mnt/create_analytics_db.sh"]
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_DB
            - name: POSTGRES_USER 
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_PASSWORD
            - name: ANALYTICS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_HOST
            - name: ANALYTICS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_NAME
            - name: ANALYTICS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_USER
            - name: ANALYTICS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_PASSWORD
      containers:
      - name: bahmni-mart
        image: mekomsolutions/bahmni-mart
        volumeMounts:
            - name: distro
              mountPath: "/var/www"
              subPath: "bahmni_config/"
            - name: mart-props-vol
              mountPath: "/opt/bahmni-mart/conf"
        env:
            - name: OPENMRS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_HOST
            - name: OPENMRS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_NAME
            - name: OPENMRS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_USER
            - name: OPENMRS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_PASSWORD
            - name: ANALYTICS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_HOST
            - name: ANALYTICS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_NAME
            - name: ANALYTICS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_USER
            - name: ANALYTICS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_PASSWORD
            - name: CRON_TIME
              value: "0/5 * * * *"