{{ if .Values.apps }}{{ if .Values.apps.bahmni_config }} {{ if .Values.apps.bahmni_config.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bahmni-config
  labels:
    app: {{ .Release.Name }}-bahmni-config
spec:
  selector:
    app: {{ .Release.Name }}-bahmni-config
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
{{ end }}{{ end }}{{ end }}