apiVersion: v1
kind: ConfigMap
metadata:
  name: openelis-db-config
  labels:
    app: openelis
data:
  OPENELIS_DB_USER: clinlims
  OPENELIS_DB_PASSWORD: clinlims
  OPENELIS_DB_NAME: clinlims
  OPENELIS_DB_HOST: postgres
  OPENELIS_ATOMFEED_USER: atomfeed
  OPENELIS_ATOMFEED_PASSWORD: AdminadMIN*
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openelis-config
  labels:
    app: openelis
data:
  atomfeed.properties: |
    #OpenMRS data specific properties
    openmrs.auth.uri=http://openmrs/openmrs/ws/rest/v1/session
    openmrs.patient.feed.uri=http://openmrs/openmrs/ws/atomfeed/patient/recent
    openmrs.encounter.feed.uri=http://openmrs/openmrs/ws/atomfeed/encounter/recent
    openmrs.lab.feed.uri=http://openmrs/openmrs/ws/atomfeed/lab/recent

    openmrs.user=superman
    openmrs.password=Admin123

    #Reference data specific properties

    reference.data.feed.uri=http://openmrs/reference-data/ws/feed/recent
    openmrs.connectionTimeoutInMilliseconds=10000
    openmrs.replyTimeoutInMilliseconds=20000
    productType.labTest=Test
    productType.panel=Panel

    #Reference data specific properties

    reference.data.feed.uri=http://openmrs/reference-data/ws/feed/recent
    reference.data.connectionTimeoutInMilliseconds=10000
    reference.data.replyTimeoutInMilliseconds=20000
  hibernate.properties: |
    hibernate.connection.url=jdbc:postgresql://postgres:5432/clinlims
    hibernate.connection.username=clinlims
    hibernate.connection.password=clinlims
    hibernate.default_schema=clinlims