apiVersion: apps/v1
kind: Deployment
metadata:
  name: openelis
spec:
  selector:
    matchLabels:
      app: openelis
  template:
    metadata:
      labels:
        app: openelis
    spec:
      volumes:
        - name: openelis-props
          configMap:
            name: openelis-config
        - name: openelis-db
          configMap:
            name: postgres-db-scripts
      initContainers:
        - name: init-db
          image: postgres:alpine
          volumeMounts:
            - name: openelis-db
              mountPath: "/mnt/"
            - name: openelis-props
              mountPath: "/sqls/"
              
          command: ['sh', '-c', "bash /mnt/create_openelis_db.sh"]
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_DB
            - name: POSTGRES_USER 
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_PASSWORD
# Odoo Vars
            - name: OPENELIS_DB_NAME 
              valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_NAME
            - name: OPENELIS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_USER
            - name: OPENELIS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_PASSWORD
            - name: OPENELIS_DB_HOST
              valueFrom:
                  configMapKeyRef:
                    name: openelis-db-config
                    key: OPENELIS_DB_HOST
      containers:
      - name: openelis
        image: enyachoke/openelis
        volumeMounts:
            - name: openelis-props
              mountPath: "/etc/properties/"
        ports:
        - containerPort: 8080
        env:
          - name: OPENELIS_DB_HOST
            valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_HOST
          - name: OPENMRS_HOST
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_HOST
          - name: OPENMRS_USER
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_USER
          - name: OPENMRS_DB_SERVER
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_DB_HOST
          - name: OPENMRS_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_DB_PASSWORD
          - name: OPENMRS_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_DB_USER
          - name: OPENMRS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_PASSWORD
          - name: OPENELIS_DB_USER
            valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_USER
          - name: OPENELIS_DB_PASSWORD
            valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_PASSWORD
          - name: OPENELIS_DB_NAME
            valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_NAME
          - name: ATOMFEED_PROPERTIES_FILE_PATH
            value: /etc/properties/atomfeed.properties
          - name: HIBERNATE_PROPERTIES_FILE_PATH
            value: /etc/properties/hibernate.properties






