{{ if .Values.nfs }}{{ if .Values.nfs.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.nfs.nfsStorageClass }}
provisioner: mekomsolutions.com/nfs
mountOptions:
  - vers=4.1
{{ end }}{{ end }}