apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  loadBalancerIP: 192.168.0.99
  type: LoadBalancer
  selector:
    app: registry
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
