apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: enyachoke/bahmniproxy
        command: ["httpd-foreground"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: proxy-rules-volume
          mountPath: /usr/local/apache2/conf/rules
        - name: proxy-config-volume
          mountPath: /usr/local/apache2/conf/extra
      volumes:
      - name: proxy-rules-volume
        configMap:
          name: proxy-rules
      - name: proxy-config-volume
        configMap:
          name: proxy-confs
