apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy-rules
data:
  proxy-rules: |
    RewriteEngine on
    RewriteCond %{REQUEST_URI} ^/$
    RewriteRule (.*) /bahmni/home [R=301,L]
    #
    ProxyPass /openelis http://{{ .Release.Name }}-openelis:8080/openelis
    ProxyPassReverse /openelis http://{{ .Release.Name }}-openelis:8080/openelis

    # OpenMRS
    ProxyPass /openmrs http://{{ .Release.Name }}-openmrs/openmrs
    ProxyPassReverse /openmrs http://{{ .Release.Name }}-openmrs/openmrs

    # Bahmni Apps
    # Bahmni Apps requires to lookup the server date. Redirecting calls to "cgi-bin/systemdate".
    ProxyPass /cgi-bin/systemdate http://{{ .Release.Name }}-bahmniapps/cgi-bin/systemdate
    ProxyPass /bahmni http://{{ .Release.Name }}-bahmniapps
    ProxyPassReverse /bahmni http://{{ .Release.Name }}-bahmniapps

    # Bahmni Config
    ProxyPass /bahmni_config http://{{ .Release.Name }}-bahmni-config
    ProxyPassReverse /bahmni_config http://{{ .Release.Name }}-bahmni-config

    # Implementer Interface
    ProxyPass /implementer-interface http://{{ .Release.Name }}-implementer-interface/implementer-interface
    ProxyPassReverse /implementer-interface http://{{ .Release.Name }}-implementer-interface/implementer-interface

    # Appointments
    ProxyPass /appointments http://{{ .Release.Name }}-appointments/appointments
    ProxyPassReverse /appointments http://{{ .Release.Name }}-appointments/appointments

    # Bahmni Home
    ProxyPass /document_images http://{{ .Release.Name }}-bahmni-filestore/document_images
    ProxyPassReverse /document_images http://{{ .Release.Name }}-bahmni-filestore/document_images
    #
    ProxyPass /clinical_forms http://{{ .Release.Name }}-bahmni-filestore/clinical_forms
    ProxyPassReverse /clinical_forms http://{{ .Release.Name }}-bahmni-filestore/clinical_forms
    #
    ProxyPass /patient_images http://{{ .Release.Name }}-bahmni-filestore/patient_images
    ProxyPassReverse /patient_images http://{{ .Release.Name }}-bahmni-filestore/patient_images
    #
    ProxyPass /reports http://{{ .Release.Name }}-bahmni-filestore/reports
    ProxyPassReverse /reports http://{{ .Release.Name }}-bahmni-filestore/reports
    #
    ProxyPass /pacs_images http://{{ .Release.Name }}-bahmni-filestore/pacs_images
    ProxyPassReverse /pacs_images http://{{ .Release.Name }}-bahmni-filestore/pacs_images
    #
    ProxyPass /uploaded_results http://{{ .Release.Name }}-bahmni-filestore/uploaded_results
    ProxyPassReverse /uploaded_results http://{{ .Release.Name }}-bahmni-filestore/uploaded_results
    #
    ProxyPass /uploaded-files http://{{ .Release.Name }}-bahmni-filestore/uploaded-files
    ProxyPassReverse /uploaded-files http://{{ .Release.Name }}-bahmni-filestore/uploaded-files

    ProxyPass /uploaded-files http://{{ .Release.Name }}-bahmni-filestore/uploaded-files
    ProxyPassReverse /uploaded-files http://{{ .Release.Name }}-bahmni-filestore/uploaded-files
    # Others
    Redirect permanent  /home  /bahmni/home/

    # Bahmni Reports
    ProxyPass /bahmni_config http://{{ .Release.Name }}-bahmni_config
    ProxyPassReverse /bahmni_config http://{{ .Release.Name }}-bahmni_config
    # Rewrite the OpenMRS Session Cookie as reporting_session Cookie for Bahmni Reports
    RewriteCond %{REQUEST_URI} ^/openmrs*
    RewriteCond %{HTTP_COOKIE} ^.*JSESSIONID=([^;]+)
    RewriteRule ^.*$ - [CO=reporting_session:%1:%{SERVER_NAME}:86400:/:false:true]