{{ if .Values.apps }}{{ if .Values.apps.implementer_interface }} {{ if .Values.apps.implementer_interface.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-implementer-interface
  labels:
    app: {{ .Release.Name }}-implementer-interface
spec:
  selector:
    app: {{ .Release.Name }}-implementer-interface
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8902
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-implementer-interface
  annotations:
    traefik.k8s.io/root-app: /implementer-interface
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-implementer-interface
          servicePort: 80
        path: /implementer-interface
{{ end }}{{ end }}{{ end }}
