{{ if .Values.apps }}{{ if .Values.apps.appointments }} {{ if .Values.apps.appointments.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-appointments
  labels:
    app: {{ .Release.Name }}-appointments
spec:
  selector:
    app: {{ .Release.Name }}-appointments
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8903
{{ end }}{{ end }}{{ end }}