deploymentProfile: onPrem
deployNfs: true
rwxStorageClass: mekom-nfs
nfsLocalPath: /mnt/disks/ssd1/nfs
postgresLocalPath: /mnt/disks/ssd1/data/postgresql
mysqlLocalPath: /mnt/disks/ssd1/data/mysql
databaseHostRole: database
nfsHostRole: database
apps:
  appointments:
    enabled: true
  bahmni-config:
    enabled: true
  bahmni-filestore:
    enabled: true
  bahmni-mart:
    enabled: true
    ANALYTICS_DB_HOST: postgres
    ANALYTICS_DB_NAME: analytics
    ANALYTICS_DB_PASSWORD: password
  bahmni-reports:
    enabled: true
  bahmniapps:
    enabled: true
  implementer-interface:
    enabled: true
  metabase:
    enabled: true
    METABASE_DB_NAME: metabase
    METABASE_DB_PASSWORD: metabase
    METABASE_DB_USER: metabase
  mysql:
    enabled: true
    MYSQL_ROOT_USER: root
    MYSQL_ROOT_PASSWORD: password
  nfs:
    enabled: true
  odoo:
    enabled: true
    ODOO_DB_USER: odoo
    ODOO_DB_PASSWORD: password
    ODOO_DB_NAME: odoo
    ODOO_HOST: odoo 
    ODOO_USER: admin
    ODOO_PASSWORD: admin
    ODOO_MASTER_PASSWORD: password
    ODOO_PUBLIC_PORT: "8069"
    ODOO_EXTRA_ADDONS: odoo_addons
    ODOO_CONFIG_PATH: odoo_config
  odoo-connect:
    enabled: true
  openelis:
    enabled: true
    OPENELIS_DB_USER: clinlims
    OPENELIS_DB_PASSWORD: clinlims
    OPENELIS_DB_NAME: clinlims
    OPENELIS_DB_HOST: postgres
    OPENELIS_ATOMFEED_USER: atomfeed
    OPENELIS_ATOMFEED_PASSWORD: AdminadMIN*
  openmrs:
    enabled: true
    OPENMRS_DB_NAME: openmrs
    OPENMRS_USER: superman
    OPENMRS_PASSWORD: Admin123
    OPENMRS_HOST: openmrs
    OPENMRS_DB_USER: openmrs
    OPENMRS_DB_HOST: mysql
    OPENMRS_DB_PASSWORD: password
    OPENMRS_OWAS_PATH: openmrs_core
    OPENMRS_MODULES_PATH: openmrs_modules
    OPENMRS_CONFIG_PATH: openmrs_config
    OPENMRS_CONFIG_CHECKSUMS_PATH: ""
  postgresql:
    enabled: true
    POSTGRES_HOST: postgres
    POSTGRES_PORT: "5432"
    POSTGRES_PASSWORD: password
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
  proxy:
    enabled: true